### ISSUE TITLE
Pydantic library errors on python 3.10

### ISSUE THREAD

**Issue by josephmckinsey** [NREL/jade#76]
When trying to use python 3.10.2, I encountered the following error. I switched my conda environment to python 3.9, and I have had no problems since then.

```
(/home/jmckinse/.conda-envs/battery) -bash-4.2$ jade config create jade_jobs.txt
Traceback (most recent call last):
  File "/home/jmckinse/.conda-envs/battery/bin/jade", line 33, in <module>
    sys.exit(load_entry_point('NREL-jade==0.7.5', 'console_scripts', 'jade')())
  File "/home/jmckinse/.conda-envs/battery/bin/jade", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/jmckinse/.conda-envs/battery/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/home/jmckinse/.conda-envs/battery/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/jmckinse/.conda-envs/battery/lib/python3.10/site-packages/jade/cli/jade.py", line 11, in <module>
    from jade.cli.cancel_jobs import cancel_jobs
  File "/home/jmckinse/.conda-envs/battery/lib/python3.10/site-packages/jade/cli/cancel_jobs.py", line 10, in <module>
    from jade.jobs.cluster import Cluster
  File "/home/jmckinse/.conda-envs/battery/lib/python3.10/site-packages/jade/jobs/cluster.py", line 10, in <module>
    from jade.jobs.job_configuration import JobConfiguration
  File "/home/jmckinse/.conda-envs/battery/lib/python3.10/site-packages/jade/jobs/job_configuration.py", line 18, in <module>
    from jade.models import submission_group
  File "/home/jmckinse/.conda-envs/battery/lib/python3.10/site-packages/jade/models/__init__.py", line 4, in <module>
    from jade.models.hpc import HpcConfig, SlurmConfig, FakeHpcConfig, LocalHpcConfig
  File "/home/jmckinse/.conda-envs/battery/lib/python3.10/site-packages/jade/models/hpc.py", line 6, in <module>
    from pydantic import Field, validator, root_validator
ImportError: cannot import name 'Field' from 'pydantic' (/home/jmckinse/.conda-envs/battery/lib/python3.10/site-packages/pydantic/__init__.py)
```

I also was unable to uninstall `nrel-jade` alone and got the following error:
```
ResolvePackageNotFound: 
  - python=3.1
```

**Comment by josephmckinsey** [comment]
Could not replicate today. Probably a momentary problem with conda.
